name: redstone_jwt_plugin
version: 0.0.2
description: Redstone Plugin for Json Web Token (JWT) authentification
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/dartsome/redstone_jwt_plugin

environment:
  sdk: ">=1.16.0 <2.0.0"

dependencies:
  redstone: ^0.6.7
  dart_jwt: any
